@startuml

title As is

|Kunde|
:Bestiller ordre;

|#AntiqueWhite|System|
:Tilføjer ordre i database;

|Fog|
:Ring til kunde og lav tilbud;

|Kunde|
:Kunde betaler fra email;

|#AntiqueWhite|System|
:Generer teknisk tegning og stykliste;

|Fog|
:Send tek. tegning og stykliste m. manual til kunde;




@enduml
