@startuml

Title Navigation

note top of Employee
Username and role
stored in session
end note

legend bottom center
Every jsp page goes to the Frontcontroller which uses javaclasses called commands to do specific operations and navigate to the next jsp page
end legend

[*] -> index

state Customer #Wheat {
index -> SubmitOrder #Salmon
SubmitOrder --> OrderConfirmation #Salmon
}

state Employee #Wheat {
index --> BrowseOrders #DodgerBlue : Login
BrowseOrders --> BrowseOrders : Update status on a specific order
BrowseOrders --> OrderInfo #DodgerBlue : Go to specific Order
OrderInfo --> OrderInfo : Edit Order
BrowseOrders --> CustomerInfo #DodgerBlue : See customer details for specific order
}

Header --> index
Employee --> Header
Customer --> Header 

Customer --> [*]
Employee --> [*] : Log out

@enduml
