@startuml

Title Navigation  for current Carport project

note top of Employee
Username and role
stored in session
end note


[*] -> index #DodgerBlue

state Customer #Wheat {
index -> ForwardToSubmitOrder #Salmon
ForwardToSubmitOrder --> submitorder #DodgerBlue
submitorder --> SubmitOrder #Salmon
SubmitOrder --> OrderConfirmation #DodgerBlue
}

state Employee #Wheat {
index --> Login #Salmon : Log in
Login --> browseorders #DodgerBlue 
browseorders --> UpdateStatus #Salmon
UpdateStatus --> browseorders : Update status on a specific order
browseorders --> ViewOrder #Salmon
ViewOrder --> orderinformation #DodgerBlue : Go to specific Order
orderinformation -> EditOrder #Salmon
EditOrder -> orderinformation : Edit Order
orderinformation --> TechnicalDrawing #Salmon
TechnicalDrawing --> techdrawing #DodgerBlue : Show technical drawing for specific order 
orderinformation --> CreateBoM #Salmon
CreateBoM --> billofmaterials #DodgerBlue : Show bill of materials for specific order
}

Employee --> index : Through header
Customer --> index : Through header

Customer --> [*]
Employee --> [*] : Log out

@enduml
