@startuml

Title Navigation

note top of Employee
Username and role
stored in session
end note
note top of Customer
Username and role
stored in session
end note

legend bottom center
Every jsp page goes to the Frontcontroller which uses javaclasses called commands to do specific operations and navigate to the next jsp page
end legend

[*] --> CustomerIndex #Salmon
[*] --> EmployeeIndex #DodgerBlue


state Customer #Wheat {
CustomerIndex --> Customerpage #Salmon : Login
Customerpage --> SubmitOrder #Salmon 
SubmitOrder --> OrderConfirmation #Salmon
CustomerHeader #Salmon --> CustomerIndex
}

state Employee #Wheat {
EmployeeIndex --> BrowseOrders #DodgerBlue : Login
BrowseOrders --> BrowseOrders : Update status on a specific order
BrowseOrders --> OrderInfo #DodgerBlue : Go to specific Order (See both order and customer detail)
BrowseOrders --> BrowseMaterials #DodgerBlue
OrderInfo --> OrderInfo : Edit Order
}

Header --> index
Employee --> Header
Customer --> Header 

Customer --> [*]
Employee --> [*] : Log out

@enduml
