@startuml

Title Navigation  for current Carport project

note top of Employee
Username and role
stored in session
end note

legend bottom center
All boxes represents jsp pages. Every jsp page goes to the Frontcontroller servlet which uses javaclasses called commands to do specific operations and navigate to the next jsp page
end legend

[*] -> index

state Customer #Wheat {
index -> SubmitOrder #Salmon
SubmitOrder --> OrderConfirmation #Salmon
}

state Employee #Wheat {
index --> BrowseOrders #DodgerBlue : Login
BrowseOrders --> BrowseOrders : Update status on a specific order
BrowseOrders --> OrderInformation #DodgerBlue : Go to specific Order
OrderInformation --> OrderInformation : Edit Order
OrderInformation --> techdrawing #DodgerBlue : Show technical drawing for specific order 
OrderInformation --> billofmaterials #DodgerBlue : Show bill of materials for specific order
}

Employee --> index : Through header
Customer --> index : Through header

Customer --> [*]
Employee --> [*] : Log out

@enduml
